### ISSUE TITLE
could you please share the tf-ckpts file ?

### ISSUE THREAD

**Issue by 15926273249** [varun0603/yolo-facemaskDetection#1]

**Comment by bejugamvarun** [comment]
I could not upload the trained file because the size of the files is pretty huge around 300mb so github is not accepting the file

**Comment by 15926273249** [comment]
Can you share this file through email, my email account is 921825229@qq.com, thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bejugamvarun/yolo-facemaskDetection"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月9日(星期五) 下午4:31
收件人:&nbsp;"bejugamvarun/yolo-facemaskDetection"<yolo-facemaskDetection@noreply.github.com&gt;;
抄送:&nbsp;"921825229"<921825229@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bejugamvarun/yolo-facemaskDetection] could you please share the tf-ckpts file ? (#1)





 
I could not upload the trained file because the size of the files is pretty huge around 300mb so github is not accepting the file
